# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'package'  # Removed 'build', assuming packaging is the main goal
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false  # Adjusted based on your requirement

- task: CopyFiles@2
  inputs:
    contents: '**/*.war'
    targetFolder: '$(System.DefaultWorkingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    artifactName: 'war'
    pathToPublish: '$(System.DefaultWorkingDirectory)'
- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Az-pipeline'
    appType: 'webAppLinux'
    WebAppName: 'Az-Java-Pipeline'
    deployToSlotOrASE: true
    ResourceGroupName: 'Aks_Rg'
    SlotName: 'production'
    packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'
    RuntimeStack: 'JAVA|11-java11'